Traceback (most recent call last):
  File "updria.py", line 87, in <module>
    main()
  File "updria.py", line 81, in main
    res = updria(opts, ts)
  File "/home/gredondi/src/updria/_updria.py", line 1131, in updria
  File "/home/gredondi/src/updria/_updria.py", line 108, in measure
    return func(*args, **kwds)
  File "/home/gredondi/src/updria/_updria.py", line 994, in recblock
  File "/home/gredondi/src/updria/_updria.py", line 821, in minimize_model
  File "/home/gredondi/.local/lib/python3.8/site-packages/z3/z3.py", line 7022, in check
  File "/home/gredondi/.local/lib/python3.8/site-packages/z3/z3core.py", line 3923, in Z3_solver_check_assumptions
  File "/home/gredondi/.local/lib/python3.8/site-packages/z3/z3core.py", line 1447, in Check
z3.z3types.Z3Exception: b'out of memory'
real 1547.38
user 1530.08
sys 16.50
